### ISSUE TITLE
Pulling together reused functions into single file

### ISSUE THREAD

**Issue by Vrroom** [Vrroom/ISL#3]
- This would involve finding what are the dependencies of a function and moving all of them to a common file which would then be imported.

**Comment by cherrybajan** [comment]
isl_util.py created and moved some functions there.

**Comment by Vrroom** [comment]
We should remove all the redundant functions in their current location and import them from this file. Also, we are missing some functions. But its a good start. Reopening the issue.

**Comment by cherrybajan** [comment]
There are a lot of such functions that could be moved to some util file, but for some of these, I dont quite know they Python syntax and so dont want to just do lift and shift. But to understand first what is going on.

**Comment by Vrroom** [comment]
I'll take care of those. Some of them are for parallel computation so I'll create a parallel utils file.
